name: graphql-apollo-client

on:
  push:
    branches:
      - main
    paths:
      - "instrumentation/rum/browser/graphql-apollo-client/**"
      - ".github/workflows/graphql-apollo-client.yml"
  pull_request:
    paths:
      - "instrumentation/rum/browser/graphql-apollo-client/**"
      - ".github/workflows/graphql-apollo-client.yml"

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: instrumentation/rum/browser/graphql-apollo-client

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: npm
          cache-dependency-path: instrumentation/rum/browser/graphql-apollo-client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: instrumentation/rum/browser/graphql-apollo-client/backend

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: npm
          cache-dependency-path: instrumentation/rum/browser/graphql-apollo-client/backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test
